site_name: textraxtras
site_author: Carlo 'carlovo' van Overbeek
site_description: Extras for Amazon's Textract API.

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  locale: en

nav:
  - Home: index.md
